[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/andante-studio/*"
  to = "https://andante-studio.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/andante-studio"
  to = "https://andante-studio.netlify.app/"
  status = 200
  force = true

Page not found

Looks like you’ve followed a broken link or entered a URL that doesn’t exist on this site.

If this is your site, and you weren’t expecting a 404 for this path, please visit Netlify’s “page not found” support guide for troubleshooting tips.
