[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/andante-studio/*"
  to = "https://andante-studio.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/andante-studio"
  to = "https://andante-studio.netlify.app/"
  status = 200
  force = true
